services:
  ahmeng-decompiler:
    build: .
    ports:
      - "5000:5000" # Backend Flask API
      - "5173:5173" # Frontend Vite dev server
    volumes:
      - ./.env:/app/backend/.env:ro
      - uploads:/tmp/uploads
      - results:/tmp/results
    restart: unless-stopped

volumes:
  uploads:
  results:
